#!/usr/bin/env bash

# Define the private key name and passphrase
PRIVATE_KEY_NAME="school"
PASSPHRASE="betty"

# Generate the RSA key pair with the specified name, bits, and passphrase
ssh-keygen -b 4096 -f "$PRIVATE_KEY_NAME" -t rsa -N  "$PASSPHRASE"
